"""empty message

Revision ID: 4cda38236c04
Revises: b8c2efba5bfd
Create Date: 2025-04-01 11:49:13.666911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cda38236c04'
down_revision = 'b8c2efba5bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_constraint('movies_title_key', type_='unique')
        batch_op.create_unique_constraint(None, ['poster'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('movies_title_key', ['title'])

    # ### end Alembic commands ###
